### ISSUE TITLE
Collect PR data from the OpenShift  Origns project for AI CoE AIops Team 

### ISSUE THREAD

**Issue by MichaelClifford** [thoth-station/mi-scheduler#130]
**Is your feature request related to a problem? Please describe.**
 
Yes, see this [issue](https://github.com/aicoe-aiops/ocp-ci-analysis/issues/146) for complete details. But I would like access to the raw PR data from the openshift origins project. 

**Describe the solution you'd like**

I would like the MI tool to collect the raw PR data from the openshift origins project. And Ideally, store it in a publicly accessible ceph bucket on operate first.  

**Describe alternatives you've considered**

The alternative to leveraging the existing MI tool would be for the AIOps team to develop their own process for collecting data from GitHub. 

**Additional context**

This is the project I would like data from: https://github.com/openshift/origin

**Comment by xtuchyna** [comment]
Hello @MichaelClifford ! You should have a PR dataset available at `s3://thoth/data/srcopsmetrics/bot_knowledge/openshift/origin/`
Please check if it's correct and sufficient for your needs :wave:  
I am currently inspecting on why the commits aggregation failed, will let you know when it'll be fixed and ready too (so you will have a `Commits.json` dataset as well.

**Comment by MichaelClifford** [comment]
@xtuchyna Thank you for your help collecting this data. 
 
Please take a look at the [open PR](https://github.com/aicoe-aiops/ocp-ci-analysis/pull/253) where we are using the data and feel free to make any comments.

What is suppose to be in the `Commits.json` file and does it exist already? If so, let me know and I think we can close this issue. :smile:

**Comment by xtuchyna** [comment]
First of all, sorry for late reply Michael!

Commit aggregation had recently undergone a change in `mi`, so currently no data is present. However, if you are still interested in code inspection, `mi` can launch one for the openshift.

Have a look here https://github.com/thoth-station/mi/pull/381/files#r633418176 on what can be collected from a repository in means of commit data, and let me know if you are interested in this kind of analysis.

**Comment by MichaelClifford** [comment]
Thanks for your help @xtuchyna I think we can close this issue. :smile:

**Comment by xtuchyna** [comment]
Thank you @MichaelClifford for closing the issue :)
