### ISSUE TITLE
Collect issues for aicoe-aiops org

### ISSUE THREAD

**Issue by MichaelClifford** [thoth-station/mi-scheduler#140]
**Describe the solution you'd like**

I would like the MI tool to collect the raw issue data from all of the **public** repos in the aicoe-aiops org. And Ideally, store it in a publicly accessible ceph bucket on operate first. Putting all issues in a single "directory" in ceph should be fine.  

**Describe alternatives you've considered**

The alternative to leveraging the existing MI tool would be for the AIOps team to develop their own process for collecting data from GitHub.

**Additional** context

This is the org I would like data from: https://github.com/aicoe-aiops

**Comment by MichaelClifford** [comment]
cc @antter

**Comment by MichaelClifford** [comment]
@xtuchyna any update on this issue :smiley:

**Comment by xtuchyna** [comment]
Hello @MichaelClifford , sorry for late response, it got somehow lost in my notifications!
Please let me know if this is still relevant, so I can schedule data aggregation today

**Comment by MichaelClifford** [comment]
Hi @xtuchyna no problem. Yes, this is still relevant. Please schedule the aggregation today.

**Comment by xtuchyna** [comment]
Data aggregation scheduled, sorry for delay - currently there are ceph data retrieval issues within `zero` cluster https://github.com/operate-first/support/issues/284 and https://github.com/operate-first/SRE/issues/347
hopefully it'll be resolved soon

**Comment by goern** [comment]
@xtuchyna where can the data be found and how be accessed?

**Comment by xtuchyna** [comment]
workflows are still waiting for the storage issue to be resolved, until then the `mi` is not able to aggregate data on zero cluster

**Comment by xtuchyna** [comment]
Hello @MichaelClifford , there are still issues within cluster (currently a small issue with service roles - probably) - https://github.com/thoth-station/thoth-application/issues/1817
I am gonna ping you back when fixed

**Comment by xtuchyna** [comment]
Hi @MichaelClifford , the data aggregation has been successfully launched today, will give you update when it completes. The data location is `s3://thoth/data/zero-test/mi/bot_knowledge/` on `http://rgw-openshift-storage.apps.zero.massopen.cloud/` endpoint

**Comment by xtuchyna** [comment]
Hello @MichaelClifford  ! The data is available, some of which however still failed to aggregate due to yet unknown issues with argo workflows on zero.

Check and see for yourself at `s3://thoth/data/zero-test/mi/bot_knowledge/` on `http://rgw-openshift-storage.apps.zero.massopen.cloud/` endpoint

Is the data in sufficient format? Or would you like having it merged into one `csv` dataset ? Please let me know and feel free to provide any other feedback

As of some missing repositories, I am still figuring out the argo issue, I've relaunched workflows so we'll see how it updates

**Comment by MichaelClifford** [comment]
@awesome thanks @xtuchyna Ill take a look and let you know : )
