### ISSUE TITLE
Collect issue,PR data for operate-first org

### ISSUE THREAD

**Issue by hemajv** [thoth-station/mi-scheduler#155]
**Describe the solution you'd like**
Collect issues, PRs, user related data available from all the repositories in the Operate First org and have it stored in a publicly accessible ceph bucket in opf. 
Related issue: https://github.com/operate-first/data-driven-development/issues/17

**Describe alternatives you've considered**
Alternative would be to use the Augur instance hosted by the OSPO team to fetch all GitHub related data available for the operate first org.

**Additional context**
Operate First org we would like to collect data for: https://github.com/operate-first

**Comment by xtuchyna** [comment]
Hello @hemajv , please let me know besides PRs and Issues what other user-related data you want us to collect.
Have a look at https://github.com/thoth-station/mi/tree/master/srcopsmetrics/entities and see if something suits you.
If there is nothing sufficient, please make a New Entity request Issue in `mi` (specifying what and which features do you want to aggregate for repos)

**Comment by xtuchyna** [comment]
Hey @hemajv ! Waiting for this https://github.com/thoth-station/thoth-application/issues/1817 to be resolved, up until then the `mi` is not able to start aggregating data

**Comment by xtuchyna** [comment]
data is available at`s3://thoth/data/zero-test/mi/bot_knowledge/operate-first` on zero cluster.
daily update not yet configured because of the recent zero cluster issues

**Comment by xtuchyna** [comment]
@hemajv feel free to leave any feedback and let me know if the data is sufficient in its current form
