### ISSUE TITLE
Make DATA_AGGREGATION_REQUEST template available when creating Issue

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi-scheduler#184]
**Is your feature request related to a problem? Please describe.**
The template is not visible right now, someone with right privileges (@harshad16 @goern ) has to set it up.

**Additional context**
Template is here https://github.com/thoth-station/mi-scheduler/tree/master/.github/ISSUE_TEMPLATE

**Comment by xtuchyna** [comment]
Related to https://github.com/thoth-station/mi/issues/410

**Comment by fridex** [comment]
The template is picked automatically once placed to .github dir. If you are referring to https://github.com/thoth-station/mi-scheduler/pull/139/files, it does not look like it obeys structure required:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

**Comment by xtuchyna** [comment]
> The template is picked automatically once placed to .github dir. If you are referring to https://github.com/thoth-station/mi-scheduler/pull/139/files, it does not look like it obeys structure required:
> 
> https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

That's right, fix on way
