### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi-scheduler#207]
Update documentation that describes the process of how `mi-scheduler` works and how data requests are made.

One of the questions that need to be answered:
```
is it the case that we just have to update this file https://github.com/thoth-station/thoth-application/blob/a23fde17dd03cc1998accccc96f827bdcdba638c/mi-scheduler/base/configmaps.yaml and then deploy mi-scheduler as an app on openshift?
```
 (by @chauhankaranraj )

/kind documentation

**Comment by chauhankaranraj** [comment]
Thanks for creating the issue @xtuchyna! 

Just to give some context around this - 
If the docs could specify the precise steps needed to configure and use `mi-scheduler`, it would help us understand how to automate the data collection process, which could be useful for the [metrics project](https://github.com/open-services-group/metrics). Related issue -  open-services-group/metrics#18

**Comment by goern** [comment]
what is the priority of this? @xtuchyna
