### ISSUE TITLE
Create knowledge parameter not recognised for kebechet workflows

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi-scheduler#215]
**Describe the bug**
When launching new merge workflow for kebechet metrics, the workflow fails with the following log:
```
Usage: cli.py [OPTIONS]
Try 'cli.py --help' for help.

Error: Invalid value for '--create-knowledge' / '-c': '' is not a valid boolean.
```

**Comment by xtuchyna** [comment]
dependency: https://github.com/thoth-station/common/issues/1247

**Comment by xtuchyna** [comment]
dependency: https://github.com/thoth-station/common/issues/1256

**Comment by xtuchyna** [comment]
dependency: https://github.com/thoth-station/mi-scheduler/issues/227

**Comment by xtuchyna** [comment]
dependency: https://github.com/thoth-station/mi-scheduler/pull/229/

**Comment by goern** [comment]
looks like most of the dependencies are closed/merged
can this be closed @xtuchyna

**Comment by goern** [comment]
@xtuchyna ping

**Comment by xtuchyna** [comment]
@goern this one got lost
of course it can be closed, it's done
