### ISSUE TITLE
Store kebechet metrics under thoth-sli-metrics

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi-scheduler#76]
**Is your feature request related to a problem? Please describe.**
See last acceptance criteria of https://github.com/thoth-station/mi/issues/331#issue-811133701

**Describe the solution you'd like**
Launch `mi` of kebechet-metrics analysis in `s3://thoth/data/{deployment-name}/thoth-sli-metrics/{repository-name}`

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> See last acceptance criteria of [thoth-station/mi#331 (comment)](https://github.com/thoth-station/mi/issues/331#issue-811133701)
> 
> **Describe the solution you'd like**
> Launch `mi` of kebechet-metrics analysis in `s3://thoth/data/{deployment-name}/thoth-sli-metrics-{environment}/`

reuse thoth env variables:

e.g.

```
THOTH_CEPH_BUCKET=thoth
THOTH_CEPH_BUCKET_PREFIX=data
THOTH_DEPLOYMENT_NAME=ocp4-stage
```

environment can be derived from THOTH_DEPLOYMENT_NAME

**Comment by pacospace** [comment]
- [ ] Path to  store daily `s3://thoth/data/{deployment-name}/thoth-sli-metrics-{environment}/kebechet-update-manager/{repository-name}` using file format ` kebechet-update-manager-2021-02-18.csv` with columns that contains datetime, timestamp and metrics defined in the list above.
