### ISSUE TITLE
Aggregate kebechet knowledge into single file

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi-scheduler#99]
**Is your feature request related to a problem? Please describe.**
Kebechet knowledge is being stored for every repo individually (#76). We need to merge that into a single file, so that overall statistics can be known (Kebechet is keeping ??? repos and etc.) 

**Describe the solution you'd like**
Make `mi-scheduler` inspect all the knowledge tree after workflows are finished and merge data into
```
s3://thoth/data/{deployment-name}/thoth-sli-metrics/kebechet-update-manager/overall-{day_date}.json
```

**Describe alternatives you've considered**
Maybe make `mi` do this merging ?

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> Kebechet knowledge is being stored for every repo individually (#76). We need to merge that into a single file, so that overall statistics can be known (Kebechet is keeping ??? repos and etc.)
> 
> **Describe the solution you'd like**
> Make `mi-scheduler` inspect all the knowledge tree after workflows are finished and merge data into
> 
> ```
> s3://thoth/data/{deployment-name}/thoth-sli-metrics/kebechet-update-manager/overall-{day_date}.json
> ```
> 
> **Describe alternatives you've considered**
> Maybe make `mi` do this merging ?

what about another component? another cronjob run every day, that check that knowledge and stores it again, something like https://github.com/thoth-station/slo-reporter/issues/210 as kebechet is related to thoth?

**Comment by goern** [comment]
sounds reasonable, I'm sure you'll find a good solution!

**Comment by xtuchyna** [comment]
All relevant PRs merged, closin this one
